/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mule.ci.tool.app;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import mule.ci.tool.app.api.APIManagerAPICaller;
import mule.ci.tool.app.api.CloudhubAPICaller;
import mule.ci.tool.app.util.AppException;

public class App {

	private static final Logger log = LoggerFactory.getLogger(App.class);

	/**
	 * APIインスタンス登録機能
	 * @throws AppException アプリケーション例外
	 */
	public static void initAPIInstance() throws AppException {
		
		APIManagerAPICaller caller = new APIManagerAPICaller();
		caller.saveAPIInstance();
	}
	
	/**
	 * APIインスタンス登録機能
	 * @throws AppException アプリケーション例外
	 */
	public static void deleteAPIInstance() throws AppException {
		
		APIManagerAPICaller caller = new APIManagerAPICaller();
		caller.deleteAPIInstance();
	}
	
	/**
	 * ポリシー・アラート機能
	 * @throws AppException アプリケーション例外
	 */
	public static void initPolicy() throws AppException {
		
		APIManagerAPICaller caller = new APIManagerAPICaller();
		caller.saveAllTier();
		caller.saveAllPolicy();
		caller.saveAllAPIAlert();
	}
	
	/**
	 * APIインスタンス削除機能
	 * @throws AppException アプリケーション例外
	 */
	public static void deletePolicy() throws AppException {
		
		APIManagerAPICaller caller = new APIManagerAPICaller();
		caller.deleteAllAPIAlert();
		caller.deleteAllPolicy();
		caller.deleteAllTier();
	}
	
	/**
	 * ランタイムアラート登録機能
	 */
	public static void initRuntimeAlert() throws AppException {
		
		CloudhubAPICaller caller = new CloudhubAPICaller();
		caller.saveAllRuntimeAlert();
	}
	
	/**
	 * ランタイムアラート登録機能
	 */
	public static void deleteRuntimeAlert() throws AppException {
		
		CloudhubAPICaller caller = new CloudhubAPICaller();
		caller.deleteAllRuntimeAlert();
	}

	public static void main(String[] args) {
		log.info("Main Process Start!!");
		try {
			initPolicy();
		} catch (AppException e) {
			log.error(e.getMessage());
		}
		log.info("Main Process Finished!!");
	}
}
