# 接続アプリケーション
connectedApplication:
  clientId: 9394559f2bb1486aa610b70986be9aba
  clientSecret: 12366977330341838C4Da68803FA6e04
  grantType: client_credentials

# 組織情報
organization:
  - bussinesGroup:
    name: SalesDept
    id: 20a8a66a-84f2-4c29-b725-bd179ed64121
    - environment
      name: development
      id: f7edb165-c18a-48fa-a739-5971221a1b7e
      clientID: 4758bdefaa45445f9f66dcb624f4e53b
      clientSercret: 779Acc635fC840749b5C3C63B863Ecc8

# 個別設定ファイル
project:
  config:
    path: project.yaml