# 接続アプリケーション
connectedApplication:
  clientId: <client Id>
  clientSecret: <client secret>
  grantType: client_credentials

# 組織情報
organization:
  <Business Group Name>:
    id: <Business Group ID>
    Dev:
      id: <Environment ID>
      clientID: <environment client ID>
      clientSercret: <environment client sercret>
    Prod:
      id: <Environment ID>
      clientID: <environment client ID>
      clientSercret: <environment client sercret>
  <Business Group Name>:
    id: <Business Group ID>
    Dev:
      id: <Environment ID>
      clientID: <Environment client ID>
      clientSercret: <Environment client sercret>
    Prod:
      id: <Environment ID>
      clientID: <Environment client ID>
      clientSercret: <Environment client sercret>

# 個別設定ファイル
project:
  config:
    path: project.yaml
    
# GitHub
github:
  accountID: <Account ID>
  repositoryID: <Repository Name>
  accessToken: <personal access token>
