/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mule.ci.tool.app;

import org.junit.Test;

import mule.ci.tool.app.util.AppException;

public class AppTest {

//	private static final Logger log = LoggerFactory.getLogger(AppTest.class);

//	@Test
	public void saveAPIInstance() throws AppException {
		App.saveAPIInstance();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
	}
	
	@Test
	public void existApplication() throws AppException {
		App.existApplication();
	}
	
//	@Test
	public void init() throws AppException {
		App.init();
	}
	
//	@Test
	public void deleteAll() throws AppException {
		App.deleteAll();
	}
	
//	@Test
	public void deleteAPIInstance() throws AppException {
		App.deleteAPIInstance();
	}
	
//	@Test
	public void savePolicies() throws AppException {
		App.savePolicies();
	}
	
//	@Test
	public void deletePolicies() throws AppException {
		App.deletePolicies();
	}
	
//	@Test
	public void saveApplication() throws AppException {
		App.saveApplication();
	}
	
//	@Test
	public void updateApplication() throws AppException {
		App.updateApplication();
	}

//	@Test
	public void saveRuntimeAlerts() throws AppException {
		App.saveRuntimeAlerts();
	}
	
//	@Test
	public void deleteRuntimeAlerts() throws AppException {
		App.deleteRuntimeAlerts();
	}
}
